# stop:  docker compose --env-file ../.env down
# start: docker compose --env-file ../.env up

name: ovi
services:
  ovi-database:
    volumes:
      # persistent storage
      #- ${DB_DATA_DIRECTORY}:/var/lib/postgresql/data

      # database always recreated
      - ${DB_SQL_ENTRYPOINT}:/docker-entrypoint-initdb.d/init.sql
    image: postgres:latest
    container_name: ovi-postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
